from datetime import date
from services.llm_client import chat


def generate_contract(
    client_name: str,
    project_name: str,
    project_value: float,
    timeline: str,
    payment_terms: str,
    freelancer_name: str,
) -> str:
    system = (
        "You are a legal document specialist for freelancers. "
        "You draft clear, professional, enforceable contracts that protect both parties. "
        "Always include a disclaimer that this is a template and professional legal review is recommended."
    )
    today = date.today().strftime("%B %d, %Y")
    prompt = f"""
Draft a complete professional freelance service contract with these details:

- Freelancer: {freelancer_name}
- Client: {client_name}
- Project: {project_name}
- Total Value: ${project_value:,.2f}
- Timeline: {timeline}
- Payment Terms: {payment_terms}
- Contract Date: {today}

Include these sections in order:

1. **Parties & Agreement Date**
2. **Project Scope & Deliverables** (use [PLACEHOLDER] for client to fill specifics)
3. **Timeline & Milestones**
4. **Payment Schedule** (based on: {payment_terms})
5. **Revision Policy** (2 rounds included, additional at hourly rate)
6. **Intellectual Property** (IP transfers on full payment)
7. **Confidentiality & NDA**
8. **Termination Clause** (notice period, kill fee)
9. **Limitation of Liability**
10. **Dispute Resolution**
11. **Signature Block** (both parties)

Use formal legal language. Mark unknowns with [PLACEHOLDER].

End with:
⚠️ *This is a template generated by AI. Please review with a qualified legal professional before use.*
"""
    return chat(prompt, system)